---

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present
- name: Start Nginx service
  ansible.builtin.service:
    name: nginx
    state: started
- name: Ensure Nginx configuration directory exists
  file:
    path: /etc/nginx/sites-available
    state: directory

- name: Create Nginx configuration file
  file:
    path: /etc/nginx/sites-available/your-website.conf
    state: touch

- name: Configure Nginx for PHP
  blockinfile:
    path: /etc/nginx/sites-available/your-website.conf
    block: |
      server {
          ...
          location ~ \.php$ {
              include snippets/fastcgi-php.conf;
              fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;  # Replace with the correct PHP version
          }
          ...
      }
- name: Create symbolic link for PHP module
  command: ln -s /etc/nginx/modules-available/mod-http-php.conf /etc/nginx/modules-enabled/
  args:
    creates: /etc/nginx/modules-enabled/mod-http-php.conf
  ignore_errors: yes
      
- name: ReStart Nginx service
  ansible.builtin.service:
    name: nginx
    state: restarted          