---
    - name: Hosting Web App From Ansible]
      hosts: all
      become: true
      tasks:
      - name: Install Apache, php and git
      apt:
        name:
        - apache2
        - php
        - php-mysql
        - git
      state: present

    - name: Restart Apache
      become: true
      systemd:
        name: apache2
        state: restarted

    - name: Remove contents of /var/www/html directory
      file:
        path: /var/www/html/
        state: absent
        # recurse: yes # is for directory
        force: yes
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        mode: '0755'
    - name: Clone User_data_IndexFile repository
      git:
        repo: https://github.com/suren-lamichhane/repo.git
        dest: /var/www/html/
        clone: yes

    - name: Install required packages
      apt:
        name:
        - python3-pymysql
        - python3-mysqldb
        - libmysqlclient-dev
        state: present
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MySQL
      apt:
        name: mysql-server
        state: present

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: true


    - name: Creating mysql user
      mysql_user:
        name: "{{db_user}}"
        password: "{{db_pass}}"
        login_unix_socket: /run/mysqld/mysqld.sock
        host: 'localhost'
        priv: '*.*:ALL'
        state: present

    - name: creating database
      mysql_db:
        name: "{{db_name}}"
      login_user: "{{db_user}}"
      login_password: "{{db_pass}}"
      # priv: '.:ALL'
      state: present